# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "configurator2"
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Flip Sasser"]
  s.date = "2012-12-26"
  s.description = ""
  s.email = "flip@getplinq.com"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".rspec",
    "Guardfile",
    "README.md",
    "Rakefile",
    "VERSION",
    "configurator.gemspec",
    "lib/configurator.rb",
    "lib/configurator/configuration.rb",
    "lib/configurator/option.rb",
    "spec/lib/configurator_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/Plinq/configurator"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "A mixin to add a .config method and options with defaults to any library"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

